### ISSUE TITLE
Compose env variable for Porkbun?

### ISSUE THREAD

**Issue by zilexa** [sabrsorensen/caddy-docker-proxy-cloudflare#2]
Hi! Finally had the chance (and forced) to renew my server. I am trying your image but I am running into an issue because I am not sure what env variable to use for porkbun. I simply followed the example you have for cloudflare `caddy.tls.dns: "porkbun {env.MY-API-TOKEN-FROM-PORKBUN}"` but this gives me an error.. invalid block being removed by caddy-docker-proxy.

this is my compose file. I am using `podman-compose` which is rootless, hence I need to add `privileged:true` to make sure it has access to the socket (verified: works). 
```
  caddy-proxy:
    container_name: caddy-proxy
    image: sabrsorensen/caddy-docker-proxy-cloudflare
    privileged: true
    restart: always
    command: docker-proxy
    networks: 
      - caddy-net
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-net
      - CADDY_DOCKER_NO_SCOPE=true
      - CADDY_DOCKER_PROXY_SERVICE_TASKS=true
      - CADDY_DOCKER_PROCESS_CADDYFILE=true
      - CLOUDFLARE_API_TOKEN=MY-PORKBUN-TOKEN
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - $DOCKERDIR/network/caddy-proxy/caddy_data:/data:Z
      - $DOCKERDIR/network/caddy-proxy/config:/config:Z
    ports:
      - 443:443
      - 80:80
    labels:
      caddy.email: $EMAIL
      caddy_0: http://cockpit.o
      caddy_0.reverse_proxy: host.docker.internal:9005
      caddy_1: http://adguard.o
      caddy_1.reverse_proxy: host.docker.internal:3000
      caddy_2: https://vpn.0
      caddy_2.reverse_proxy: host.docker.internal:5000
      caddy_2: https://unifi.o
      caddy_2.reverse_proxy: host.docker.internal:8080
```

For a container say Vaultwarden I have:
```
##_____________________ Bitwarden [CLOUD/Password-manager] 
  vaultwarden:
    container_name: cloud-vaultwarden
    image: vaultwarden/server
    restart: always
    healthcheck:
      interval: 5m # to test the container, change to 10s. To prevent constant logfile activity, change to a few minutes
    networks: 
      - caddy-net
    environment:
      TZ: $TZ
      WEBSOCKET_ENABLED: true
      DOMAIN: https://vault.$DOMAIN
      SIGNUPS_ALLOWED: false
      ADMIN_TOKEN: $VAULTWARDENTOKEN
    volumes:
      - $DOCKERDIR/cloud/vaultwarden:/data:Z
    labels:
      caddy: vault.$DOMAIN
      caddy.reverse_proxy_0: "{{upstreams 80}}"
      caddy.tls.dns: "porkbun {env.MY-PORKBUN-TOKEN}"
      # Required extra headers
      caddy.encode: gzip
      caddy.header.X-XSS-Protection: '"1; mode=block;"'
      caddy.header.X-Frame-Options: "DENY"
      caddy.header.X-Content-Type-Options: "none"
      caddy.reverse_proxy_1: "/notifications/hub/negotiate {{upstreams 80}}"
      caddy.reverse_proxy_2: "/notifications/hub {{upstreams 3012}}"
```

but this shows:
```
[ERROR]  Removing invalid block: parsing caddyfile tokens for 'tls': Caddyfile:45 - Error during parsing: getting DNS provider module named 'porkbun': module not registered: dns.providers.porkbun
```

Hope you can help out!
